### ISSUE TITLE
fail to build SS-bond

### ISSUE THREAD

**Issue by xtzhang0216** [YuzheWangPKU/DiffPepBuilder#15]
Congratulations on this great work!
I have encountered a problem when running the alk1 demo. Most designed peptides are alpha-helix or loop, I haven't seen SSbond. How can I fix it?

this is my inference.yaml
```
# Configuration for de novo peptide generation.

defaults:
  - eval_gen

data:
  train_csv_path: null
  # CSV for path and metadata to receptors.
  val_csv_path: ${oc.env:BASE_PATH}/data/receptor_data/metadata_test.csv
  num_eval_samples: null

  # Add Gaussian noise to center position.
  center_pos_noise: True
  center_pos_noise_std: 5.0

experiment:
  # Experiment metadata
  name: inference

  # Training mode
  use_ddp : True

  # Training arguments
  eval_batch_size: ${inference.sampling.samples_per_length}
  num_loader_workers: 4
  use_gpu: True
  num_gpus: 8
  sample_mode: time_batch

  # Evaluation.
  eval_ckpt_path: ${oc.env:BASE_PATH}/experiments/checkpoints/diffpepbuilder_v1.pth
  eval_dir: ${oc.env:BASE_PATH}/tests

inference:
  seed: 42

  # Save the denoising trajectory.
  save_traj: False

  denoising:
    # Number of steps.
    num_t: 200
    # Analogous to sampling temperature.
    noise_scale: 1.0
    # Final t.
    min_t: 0.01

  sampling:
    # Number of peptide backbone samples per sequence length.
    samples_per_length: 8
    # Minimum sequence length to sample.
    min_length: 8
    # Maximum sequence length to sample.
    max_length: 30
    # Sampling temperature.
    seq_temperature: 0.1

  ss_bond:
    # Calculate and save the entropy of each residue as B factors
    save_entropy: True
    # Build disulfide bonds
    build_ss_bond: True
    # Maximum number of SS bonds
    max_ss_bond: 2
    # Disulfide bond fragment library path
    frag_lib_path: ${oc.env:BASE_PATH}/SSbuilder/SSBLIB
    # b-factor threshold
    entropy_threshold: 0.01
```
Thanks in advance
