### ISSUE TITLE
How to generate peptides in multiple batches

### ISSUE THREAD

**Issue by amin-sagar** [YuzheWangPKU/DiffPepBuilder#4]
Hello.
Thanks for this awesome work.
I am trying to find a way to generate a large number of peptides without running out of memory. I tried modifying the provided inference.yaml file as follows 
```
 # Training mode
  use_ddp : False

  # Training arguments
  #eval_batch_size: ${inference.sampling.samples_per_length}
  eval_batch_size: 64
  batch_size: 64
  num_loader_workers: 4
  use_gpu: True
  num_gpus: 1
  sample_mode: time_batch

  # Evaluation.
  eval_ckpt_path: ${oc.env:BASE_PATH}/experiments/checkpoints/diffpepbuilder_v1.pth
  eval_dir: ${oc.env:BASE_PATH}/tests

inference:
  seed: 42

  # Save the denoising trajectory.
  save_traj: False

  denoising:
    # Number of steps.
    num_t: 200
    # Analogous to sampling temperature.
    noise_scale: 1.0
    # Final t.
    min_t: 0.01

  sampling:
    # Number of peptide backbone samples per sequence length.
    samples_per_length: 128
    # Minimum sequence length to sample.
    min_length: 8
```
But this generates only 64 peptides.
Can you please tell me how I can generate 256 peptides in total, for example, by generating 64 at a time?
Best,
Amin.
